# Generated by Django 3.1.5 on 2021-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_image',
            field=models.ImageField(upload_to='bosch_production_app/uploaded_profile_pics'),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='profile_image',
            field=models.ImageField(upload_to='bosch_production_app/uploaded_profile_pics'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='profile_image',
            field=models.ImageField(upload_to='bosch_production_app/uploaded_profile_pics'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='profile_image',
            field=models.ImageField(upload_to='bosch_production_app/uploaded_profile_pics'),
        ),
    ]
